/**
 * spaintgui: Application.h
 * Copyright (c) Torr Vision Group, University of Oxford, 2015. All rights reserved.
 */

#ifndef H_SPAINTGUI_APPLICATION
#define H_SPAINTGUI_APPLICATION

#ifdef _MSC_VER
  // Suppress some VC++ warnings that are produced by boost/asio.hpp.
  #pragma warning(disable:4267)
#endif

#include <boost/asio.hpp>
#include <boost/filesystem.hpp>

#ifdef _MSC_VER
  // Re-enable the VC++ warnings for the rest of the code.
  #pragma warning(default:4267)
#endif

#include <SDL.h>

// Suppress the definition of M_PI provided by SDL - we want the one in <cmath>.
#ifdef M_PI
#undef M_PI
#endif

#include <tvginput/InputState.h>

#include <tvgutil/commands/CommandManager.h>

#include "core/Pipeline.h"
#include "renderers/Renderer.h"

/**
 * \brief The main application class for spaintgui.
 */
class Application
{
  //#################### TYPEDEFS ####################
private:
  typedef boost::shared_ptr<Renderer> Renderer_Ptr;
  typedef Renderer::RenderState_CPtr RenderState_CPtr;

  //#################### PRIVATE VARIABLES ####################
private:
  /** The command manager. */
  tvgutil::CommandManager m_commandManager;

  /** The current state of the keyboard and mouse. */
  tvginput::InputState m_inputState;

  /** The pipeline that the application should use. */
  Pipeline_Ptr m_pipeline;

  /** The current renderer. */
  Renderer_Ptr m_renderer;

  /** The stream of commands being sent from the voice command server. */
  boost::asio::ip::tcp::iostream m_voiceCommandStream;

  //#################### CONSTRUCTORS ####################
public:
  /**
   * \brief Constructs the application.
   *
   * \param pipeline  The pipeline that the application should use.
   */
  explicit Application(const Pipeline_Ptr& pipeline);

  //#################### PUBLIC MEMBER FUNCTIONS ####################
public:
  /**
   * \brief Runs the application.
   */
  void run();

  //#################### PUBLIC STATIC MEMBER FUNCTIONS ####################
public:
  /**
   * \brief Gets the path to the resources directory.
   *
   * \return  The path to the resources directory.
   */
  static boost::filesystem::path resources_dir();

  //#################### PRIVATE MEMBER FUNCTIONS ####################
private:
  /**
   * \brief Gets the current monocular render state.
   *
   * If we're rendering in stereo, this will return the render state corresponding to the left eye.
   *
   * \return  The current monocular render state.
   */
  Renderer::RenderState_CPtr get_monocular_render_state() const;

  /**
   * \brief Handle key down events.
   *
   * \param keysym  A representation of the key that has been pressed.
   */
  void handle_key_down(const SDL_Keysym& keysym);

  /**
   * \brief Handle key up events.
   *
   * \param keysym  A representation of the key that has been released.
   */
  void handle_key_up(const SDL_Keysym& keysym);

  /**
   * \brief Handle mouse button down events.
   *
   * \param e The mouse button down event.
   */
  void handle_mousebutton_down(const SDL_MouseButtonEvent& e);

  /**
   * \brief Handle mouse button up events.
   *
   * \param e The mouse button up event.
   */
  void handle_mousebutton_up(const SDL_MouseButtonEvent& e);

  /**
   * \brief Processes user input that deals with the camera.
   */
  void process_camera_input();

  /**
   * \brief Processes user input that deals with commands (i.e. undo/redo).
   */
  void process_command_input();

  /**
   * \brief Processes any SDL events (e.g. those generated by user input).
   *
   * \return true, if the application should continue running, or false otherwise.
   */
  bool process_events();

  /**
   * \brief Takes action as relevant based on the current input state.
   */
  void process_input();

  /**
   * \brief Processes user input that deals with labelling the scene.
   */
  void process_labelling_input();

  /**
   * \brief Processes user input that deals with switching pipeline mode.
   */
  void process_mode_input();

  /**
   * \brief Processes user input that deals with switching the renderer or raycast type.
   */
  void process_renderer_input();

  /**
   * \brief Processes voice input from the user.
   */
  void process_voice_input();

  /**
   * \brief Sets up the semantic labels with which the user can label the scene.
   */
  void setup_labels();
};

#endif
