###################
# LinkVicon.cmake #
###################

IF(WITH_VICON)
  TARGET_LINK_LIBRARIES(${targetname} ${VICON_DATASTREAM_LIBRARY} ${VICON_DEBUGSERVICES_LIBRARY})

  ADD_CUSTOM_COMMAND(TARGET ${targetname} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${VICON_DATASTREAM_LIBRARY} $<TARGET_FILE_DIR:${targetname}>)
  ADD_CUSTOM_COMMAND(TARGET ${targetname} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${VICON_DEBUGSERVICES_LIBRARY} $<TARGET_FILE_DIR:${targetname}>)
ENDIF()
