#####################
# UseGraphviz.cmake #
#####################

OPTION(WITH_GRAPHVIZ "Build with Graphviz support?" OFF)

IF(WITH_GRAPHVIZ)
  IF(MSVC_IDE)
    FIND_PATH(GRAPHVIZ_ROOT include/graphviz/cgraph.h HINTS "C:/Program Files (x86)/Graphviz2.38")
  ENDIF()

  FIND_PATH(GRAPHVIZ_INCLUDE_DIR graphviz/cgraph.h HINTS "${GRAPHVIZ_ROOT}/include")

  SET(GRAPHVIZ_LIBDIR_DEBUG "${GRAPHVIZ_ROOT}/lib/debug/lib")
  SET(GRAPHVIZ_LIBDIR_RELEASE "${GRAPHVIZ_ROOT}/lib/release/lib")

  FIND_LIBRARY(CDT_LIBRARY_DEBUG cdt HINTS ${GRAPHVIZ_LIBDIR_DEBUG})
  FIND_LIBRARY(CGRAPH_LIBRARY_DEBUG cgraph HINTS ${GRAPHVIZ_LIBDIR_DEBUG})
  FIND_LIBRARY(GVC_LIBRARY_DEBUG gvc HINTS ${GRAPHVIZ_LIBDIR_DEBUG})

  FIND_LIBRARY(CDT_LIBRARY_RELEASE cdt HINTS ${GRAPHVIZ_LIBDIR_RELEASE})
  FIND_LIBRARY(CGRAPH_LIBRARY_RELEASE cgraph HINTS ${GRAPHVIZ_LIBDIR_RELEASE})
  FIND_LIBRARY(GVC_LIBRARY_RELEASE gvc HINTS ${GRAPHVIZ_LIBDIR_RELEASE})

  SET(CDT_LIBRARY debug ${CDT_LIBRARY_DEBUG} optimized ${CDT_LIBRARY_RELEASE})
  SET(CGRAPH_LIBRARY debug ${CGRAPH_LIBRARY_DEBUG} optimized ${CGRAPH_LIBRARY_RELEASE})
  SET(GVC_LIBRARY debug ${GVC_LIBRARY_DEBUG} optimized ${GVC_LIBRARY_RELEASE})

  SET(GRAPHVIZ_LIBRARIES ${CDT_LIBRARY} ${CGRAPH_LIBRARY} ${GVC_LIBRARY})

  INCLUDE_DIRECTORIES(${GRAPHVIZ_INCLUDE_DIR})
  ADD_DEFINITIONS(-DWITH_GRAPHVIZ)
ENDIF()
