#####################
# UseGraphviz.cmake #
#####################

OPTION(WITH_GRAPHVIZ "Build with Graphviz support?" OFF)

IF(WITH_GRAPHVIZ)
  IF(MSVC_IDE)
    FIND_PATH(GRAPHVIZ_BINDIR dot.exe HINTS "C:/Program Files (x86)/Graphviz2.38/bin")
  ENDIF()

  FIND_PROGRAM(GRAPHVIZ_DOT dot HINTS ${GRAPHVIZ_BINDIR})
  FIND_PROGRAM(GRAPHVIZ_NEATO neato HINTS ${GRAPHVIZ_BINDIR})

  ADD_DEFINITIONS(-DWITH_GRAPHVIZ)
  ADD_DEFINITIONS(-DGRAPHVIZ_DOT=${GRAPHVIZ_DOT})
  ADD_DEFINITIONS(-DGRAPHVIZ_NEATO=${GRAPHVIZ_NEATO})
ENDIF()
