################
# UseSDL.cmake #
################

IF(MSVC_IDE)
  FIND_PATH(SDL_INCLUDE_DIR SDL.h HINTS "${PROJECT_SOURCE_DIR}/libraries/SDL2-2.0.3/install/include/SDL2")
  FIND_LIBRARY(SDL_LIBRARY SDL2 HINTS "${PROJECT_SOURCE_DIR}/libraries/SDL2-2.0.3/install/lib")
  FIND_LIBRARY(SDLMAIN_LIBRARY SDL2main HINTS "${PROJECT_SOURCE_DIR}/libraries/SDL2-2.0.3/install/lib")
ELSE()
  FIND_PATH(SDL_INCLUDE_DIR SDL.h HINTS "${PROJECT_SOURCE_DIR}/libraries/SDL2-2.0.3/include")
  FIND_LIBRARY(SDL_LIBRARY SDL2-2.0 HINTS "${PROJECT_SOURCE_DIR}/libraries/SDL2-2.0.3/build")
  FIND_LIBRARY(SDLMAIN_LIBRARY SDL2main HINTS "${PROJECT_SOURCE_DIR}/libraries/SDL2-2.0.3/build")
ENDIF()

INCLUDE_DIRECTORIES(${SDL_INCLUDE_DIR})
